spring:
  application:
    name: easyEvent
  datasource:
    url: jdbc:mariadb://localhost:3308/easy_event
    username: root
    password: 1604
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: c321632aae2b5c60e20afd92fdcb3751650fb09646b8661de7fa7d9bfe1df569
