spring:
  application:
    name: easyEvent
  datasource:
    url: jdbc:mariadb://localhost:3306/easyEvent
    username: root
    password: 1604

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
